### PR TITLE
Update react-router-dom version to 6.4.3

### PR DESCRIPTION
**Pull request by ppchart**

### CODE REVIEW

**Comment by robinv8** [comment]
@ppchart Upgrading the version of the dependent library may cause other problems, which needs to be handled internally by us

**Comment by ppchart** [comment]
@robinv8 This PR should not be merged until dependencies are upgraded
https://github.com/answerdev/answer/pull/17

**Comment by robinv8** [comment]
revert #60

Let's discuss internally

**Comment by robinv8** [comment]
@ppchart You mentioned a PR that limits pnpm

**Comment by ppchart** [comment]
https://github.com/answerdev/answer/pull/62

Submitted a PR that only supports pnpm. If we tell users that only pnpm is supported, the problem of the wrong version of react-router-dom after installing dependencies on npm can be ignored

-----------
提交了一个只支持 pnpm 的 PR，如果我们告诉用户只支持使用 pnpm，针对 npm 安装依赖后 react-router-dom 版本错误的问题就可以被忽略了

**Comment by robinv8** [comment]
Thanks for the contribution

**Pull request closed without merging**
